// Generated by scripts/generate_catalog.py. Edit data/catalog.json.
module.exports = {
  "defaults": [
    1,
    2,
    3,
    4,
    5,
    0,
    0
  ],
  "options": [
    {
      "label": "Empty",
      "value": "0"
    },
    {
      "label": "Preces",
      "value": "1"
    },
    {
      "label": "Holy Rosary",
      "value": "2"
    },
    {
      "label": "Regina Caeli",
      "value": "3"
    },
    {
      "label": "Angelus",
      "value": "4"
    },
    {
      "label": "Memorare",
      "value": "5"
    },
    {
      "label": "Litany of Loreto",
      "value": "6"
    },
    {
      "label": "More Prayers",
      "value": "7"
    },
    {
      "label": "Mental Prayer",
      "value": "8"
    },
    {
      "label": "Visit & Communion",
      "value": "9"
    },
    {
      "label": "Before Work",
      "value": "10"
    },
    {
      "label": "Night Examination",
      "value": "11"
    },
    {
      "label": "Confession",
      "value": "12"
    },
    {
      "label": "Examination",
      "value": "13"
    },
    {
      "label": "Act of Contrition",
      "value": "14"
    },
    {
      "label": "Before Confession",
      "value": "15"
    },
    {
      "label": "After Confession",
      "value": "16"
    },
    {
      "label": "Psalm 50 (51)",
      "value": "17"
    },
    {
      "label": "Acceptance of Death",
      "value": "18"
    },
    {
      "label": "Prayer for Vocations",
      "value": "19"
    },
    {
      "label": "Blessed Be Your Purity",
      "value": "20"
    },
    {
      "label": "Canticle of the Three Children",
      "value": "21"
    },
    {
      "label": "Psalm 2",
      "value": "22"
    },
    {
      "label": "Aspirations",
      "value": "23"
    },
    {
      "label": "Prayer Cards",
      "value": "24"
    },
    {
      "label": "Card: St. Josemaría Escrivá",
      "value": "25"
    },
    {
      "label": "Card: Bl. Álvaro del Portillo",
      "value": "26"
    },
    {
      "label": "Card: Bl. Guadalupe Ortiz de Landázuri",
      "value": "27"
    },
    {
      "label": "Card: Ven. Isidoro Zorzano",
      "value": "28"
    },
    {
      "label": "Card: Ven. Montse Grases",
      "value": "29"
    },
    {
      "label": "Card: Dora del Hoyo",
      "value": "30"
    },
    {
      "label": "Card: Fr. Joseph Múzquiz",
      "value": "31"
    },
    {
      "label": "Card: Fr. José María Hernández Garnica",
      "value": "32"
    },
    {
      "label": "Card: Toni Zweifel",
      "value": "33"
    },
    {
      "label": "Card: Ernesto Cofiño",
      "value": "34"
    },
    {
      "label": "Card: Encarnita Ortega",
      "value": "35"
    },
    {
      "label": "Card: Tomás & Paquita Alvira",
      "value": "36"
    },
    {
      "label": "Card: Laura & Eduardo Ortiz de Landázuri",
      "value": "37"
    },
    {
      "label": "Card: Pedro Ballester",
      "value": "38"
    }
  ]
};
