#!/usr/bin/env python3
"""Package resource-backed C prayer literals verbatim, including terminating NULs."""
import argparse
import ast
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser()
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
source = (ROOT / 'src/c/prayers.c').read_text()
outputs = {}
headers = {}
for symbol, filename, header, macro in [
    ('s_preces_latin', 'preces', 'preces_resource', 'PRECES'),
    ('s_come_holy_spirit_english', 'come-holy-spirit',
     'additional_prayer_resources', 'COME_HOLY_SPIRIT'),
    ('s_litany_of_humility_english', 'litany-of-humility',
     'additional_prayer_resources', 'LITANY_OF_HUMILITY'),
]:
    match = re.search(r'static const char ' + symbol + r'\[\] =\s*((?:"(?:[^"\\]|\\.)*"\s*)+);', source, re.S)
    assert match, f'Missing canonical literal: {symbol}'
    text = ''.join(ast.literal_eval(s) for s in re.findall(r'"(?:[^"\\]|\\.)*"', match[1]))
    data = text.encode('utf-8') + b'\0'
    outputs[f'resources/data/{filename}.bin'] = data
    headers.setdefault(header, '// Generated by scripts/generate_text_resource.py.\n#pragma once\n')
    headers[header] += f'#define {macro}_RESOURCE_BYTES {len(data)}\n'
outputs.update({f'src/c/{name}.h': content.encode() for name, content in headers.items()})
for name, data in outputs.items():
    path = ROOT / name
    if args.check:
        assert path.read_bytes() == data, f'{name} is stale; run scripts/generate_text_resource.py'
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)
