#!/usr/bin/env python3
"""Generate the native wordmark mask from the launcher PNG (requires Pillow)."""
from pathlib import Path
from PIL import Image

root=Path(__file__).resolve().parents[1]
with Image.open(root/'resources/images/orationes-menu-icon.png') as image:
    image=image.convert('RGBA')
    assert image.size==(25,25)
    rows=[sum(1<<x for x in range(25) if image.getpixel((x,y))[3]==255) for y in range(25)]
(root/'src/c/brand_icon.inc').write_text(
    '// Generated by scripts/generate_brand_icon.py from the launcher PNG.\n'
    'static const uint32_t s_brand_icon_rows[25] = {\n'+
    ''.join(f'  0x{row:08x},\n' for row in rows)+'};\n')
