#!/usr/bin/env python3
"""Package the canonical C Preces literal verbatim, including its terminating NUL."""
import argparse
import ast
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser()
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
source = (ROOT / 'src/c/prayers.c').read_text()
match = re.search(r'static const char s_preces_latin\[\] =\s*((?:"(?:[^"\\]|\\.)*"\s*)+);', source, re.S)
assert match, 'Missing canonical Preces literal'
text = ''.join(ast.literal_eval(s) for s in re.findall(r'"(?:[^"\\]|\\.)*"', match[1]))
outputs = {
    'resources/data/preces.bin': text.encode('utf-8') + b'\0',
    'src/c/preces_resource.h': ('// Generated by scripts/generate_text_resource.py.\n'
        '#pragma once\n#define PRECES_RESOURCE_BYTES %d\n' % (len(text.encode('utf-8'))+1)).encode(),
}
for name, data in outputs.items():
    path = ROOT / name
    if args.check:
        assert path.read_bytes() == data, f'{name} is stale; run scripts/generate_text_resource.py'
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)
