#!/usr/bin/env python3
"""Generate watch and phone catalog definitions without modifying prayer text."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser()
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
catalog = json.loads((ROOT / 'data/catalog.json').read_text())
entries = catalog['entries']
assert [e['id'] for e in entries] == list(range(len(entries)))
assert len({e['symbol'] for e in entries}) == len(entries)
assert len(catalog['defaults']) == 7
assert all(0 <= e['category'] < len(catalog['categories']) for e in entries)
for symbol, number in json.loads((ROOT / 'tests/catalog-ids.json').read_text()).items():
    assert entries[number]['symbol'] == symbol, f'Persisted ID changed: {symbol}'
quote = lambda s: json.dumps(s, ensure_ascii=False)
header = '// Generated by scripts/generate_catalog.py. Edit data/catalog.json.\n#pragma once\n\ntypedef enum {\n'
header += ''.join(f"  {e['symbol']} = {e['id']},\n" for e in entries)
header += f'  MAIN_MENU_ENTRY_COUNT = {len(entries)},\n}} MainMenuEntryId;\n'
source = '// Generated by scripts/generate_catalog.py. Edit data/catalog.json.\n'
source += 'const uint8_t main_menu_default_slots[7] = {' + ', '.join(map(str, catalog['defaults'])) + '};\n'
source += 'static const char *const s_categories[] = {' + ', '.join(map(quote, catalog['categories'])) + '};\n'
source += 'static const MainMenuEntry s_entries[] = {\n'
source += ''.join(f"  [{e['symbol']}] = {{{quote(e['name'])}, {e['destination']}, {e['target']}, {e['item']}, {e['category']}}},\n" for e in entries)
source += '};\n'
js = '// Generated by scripts/generate_catalog.py. Edit data/catalog.json.\nmodule.exports = '
js += json.dumps({'defaults': catalog['defaults'], 'options': [dict(label=e['phone_name'], value=str(e['id'])) for e in entries]}, ensure_ascii=False, indent=2) + ';\n'
for name, content in {'src/c/catalog_ids.h': header, 'src/c/catalog_entries.inc': source, 'src/pkjs/catalog.js': js}.items():
    path = ROOT / name
    if args.check:
        assert path.read_text() == content, f'{name} is stale; run python3 scripts/generate_catalog.py'
    else:
        path.write_text(content)
