#include "litany.h"

static const char s_litany_of_loreto[] =
    "Lord, have mercy on us. Christ, have mercy on us.\n\n"
    "Lord, have mercy on us. Christ, hear us.\n"
    "Christ, graciously hear us.\n\n"
    "God the Father of heaven.\n"
    "Have mercy on us.\n\n"
    "God the Son, redeemer of the world.\n"
    "Have mercy on us.\n\n"
    "God the Holy Spirit.\n"
    "Have mercy on us.\n\n"
    "Holy Trinity, one God. Have mercy on us.\n\n"
    "Holy Mary.\n"
    "Pray for us\n"
    "Holy Mother of God.\n"
    "Holy Virgin of virgins.\n"
    "Mother of Christ.\n"
    "Mother of the Church.\n"
    "Mother of mercy.\n"
    "Mother of divine grace.\n"
    "Mother of hope.\n"
    "Mother most pure.\n"
    "Mother most chaste.\n"
    "Mother inviolate.\n"
    "Mother undefiled.\n"
    "(Mother immaculate.)\n"
    "Mother most amiable.\n"
    "Mother most admirable.\n"
    "Mother of good counsel.\n"
    "Mother of our Creator.\n"
    "Mother of our Savior.\n"
    "Virgin most prudent.\n"
    "Virgin most venerable.\n"
    "Virgin most renowned.\n"
    "Virgin most powerful.\n"
    "Virgin most merciful.\n"
    "Virgin most faithful.\n"
    "Mirror of justice.\n"
    "Seat of wisdom.\n"
    "Cause of our joy.\n"
    "Spiritual vessel.\n"
    "Vessel of honor.\n"
    "Singular vessel of devotion.\n"
    "Mystical rose.\n"
    "Tower of David.\n"
    "Tower of ivory.\n"
    "House of gold.\n"
    "Ark of the covenant.\n"
    "Gate of heaven.\n"
    "Morning star.\n"
    "Health of the sick.\n"
    "Refuge of sinners.\n"
    "Solace of migrants.\n"
    "Comforter of the afflicted.\n"
    "Help of Christians.\n"
    "Queen of angels.\n"
    "Queen of patriarchs.\n"
    "Queen of prophets.\n"
    "Queen of apostles.\n"
    "Queen of martyrs.\n"
    "Queen of confessors.\n"
    "Queen of virgins.\n"
    "Queen of all saints.\n"
    "Queen conceived without original sin.\n"
    "Queen assumed into heaven.\n"
    "Queen of the most holy Rosary.\n"
    "Queen of the family\n"
    "Queen of peace.\n\n"
    "V. Lamb of God who takes away the sins of the world.\n"
    "R. Spare us, O Lord.\n\n"
    "V. Lamb of God, who takes away the sins of the world.\n"
    "R. Graciously hear us, O Lord.\n\n"
    "V. Lamb of God, who takes away the sins of the world.\n"
    "R. Have mercy on us.\n\n"
    "V. Pray for us, O holy Mother of God.\n"
    "R. That we may be made worthy of the promises of Christ.\n\n"
    "Other Intentions\n\n"
    "For the needs of the Church and of the Nation.\n"
    "Our Father... Hail Mary... Glory Be...\n\n"
    "For the (Arch)Bishop of this diocese and his intentions.\n"
    "Our Father... Hail Mary... Glory Be...\n\n"
    "For the holy souls in purgatory.\n"
    "Our Father... Hail Mary...\n\n"
    "May they rest in peace. Amen.";

const char *litany_of_loreto_text(void) {
  return s_litany_of_loreto;
}
